variables:
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/InvSync-*.jar*"
  ARTIFACTS: "$CI_PROJECT_DIR/InvSync-*.jar*"

cache:
  untracked: false

stages:
- build
- deploy
  
build:
  stage: build
  script:
  - ./gradlew --console=plain assemble -Psigning.keyId="$keyId" -Psigning.password="$password" -Psigning.secretKeyRingFile="$secretKeyRingFile"
  - cp $ORIG_ARTIFACTS .
  when: on_success
  except:
    - tags
  artifacts:
    name: "InvSync-$(cat \"$CI_PROJECT_DIR/build/.version\")"
    paths:
    - $ARTIFACTS
    
deploy:
  stage: deploy
  script:
  - ./gradlew --console=plain uploadArchives -Psigning.keyId="$keyId" -Psigning.password="$password" -Psigning.secretKeyRingFile="$secretKeyRingFile"
  when: on_success
  only:
  - tags
