name: Language File Checks

on:
  push:
    paths:
      - '**/resources/assets/*/lang/*.lang'
  pull_request_target:
    paths:
      - '**/resources/assets/*/lang/*.lang'
  workflow_dispatch:

env:
  GRADLE_OPTS: >-
    -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
  GRADLE_CMD_OPTS: >-
    --continue
    --no-build-cache
    --no-daemon
    --parallel

jobs:
  checkTranslations:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: burrunan/gradle-cache-action@v1
        name: Check Translation files for completenes
        with:
          # Properties are passed as -Pname=value
          properties: |
            branchName=${{ github.ref }}
          # Arguments for Gradle execution
          arguments: ${{ env.GRADLE_CMD_OPTS }} checkTranslations
          # Enable concurrent cache save and restore (it's faster)
          concurrent: true
      - name: Print checkTranslations report files
        if: failure()
        run: tail -n +1 *.lang.txt
      #- name: Publish Language File Checks
      #  if: success() || failure()
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: checkTranslations
      #    path: '**.lang.txt'
